project_id = "rrvcevhcocsbnsobkdzt"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-sms]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-newsletter-welcome]
verify_jwt = false

[functions.shopping-assistant]
verify_jwt = false
